テスト

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -18,7 +18,15 @@ on:
     # paths:
     #   - "apps/manage/**"
 jobs:
-  test:
-    name: Execute React Test
-    if: ${{ github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'tested' }}
+  validate-branches:
     runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout the code
+        uses: actions/checkout@v4
+
+      - name: Fail if branch conditions are not met
+        if: ${{ github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'tested' }}
+        run: |
+          echo "Error: Branch conditions are not met."
+          exit 1
