リファkつ

diff --git a/.github/workflows/validate-release-pr.yml b/.github/workflows/validate-release-pr.yml
--- a/.github/workflows/validate-release-pr.yml
+++ b/.github/workflows/validate-release-pr.yml
@@ -5,8 +5,6 @@ on:
     types:
       - opened
       - synchronize
-      # - reopened
-      # 仮にmainが更新された時に、このワークフローが走らないようにするため、更新と再オープンのイベントを追加
 
 jobs:
   validate-branches:
@@ -16,8 +14,27 @@ jobs:
       - name: Checkout the code
         uses: actions/checkout@v4
 
-      - name: Fail if branch conditions are not met
-        if: ${{ github.event.pull_request.head.ref == 'production' || (github.event.pull_request.head.ref == 'staging' && github.event.pull_request.base.ref != 'production') || (github.event.pull_request.base.ref == 'staging' && github.event.pull_request.head.ref != 'main') || (github.event.pull_request.base.ref == 'production' && github.event.pull_request.head.ref != 'staging') || (github.event.pull_request.base.ref == 'main' && (github.event.pull_request.head.ref == 'production' || github.event.pull_request.head.ref == 'staging')) }}
+      - name: Set environment variables for branches
+        env:
+          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
+          HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
         run: |
-          echo "Error: Branch conditions are not met."
-          exit 1
+          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
+          echo "HEAD_BRANCH=$HEAD_BRANCH" >> $GITHUB_ENV
+
+      - name: Define branch conditions
+        run: |
+          # Load environment variables
+          source $GITHUB_ENV
+
+          # Define branch conditions
+          IS_HEAD_PRODUCTION=$([[ "$HEAD_BRANCH" == "production" ]])
+          IS_HEAD_STAGING_BASE_NOT_PRODUCTION=$([[ "$HEAD_BRANCH" == "staging" && "$BASE_BRANCH" != "production" ]])
+          IS_BASE_STAGING_HEAD_NOT_MAIN=$([[ "$BASE_BRANCH" == "staging" && "$HEAD_BRANCH" != "main" ]])
+          IS_BASE_PRODUCTION_HEAD_NOT_STAGING=$([[ "$BASE_BRANCH" == "production" && "$HEAD_BRANCH" != "staging" ]])
+          IS_BASE_MAIN_HEAD_PRODUCTION_OR_STAGING=$([[ "$BASE_BRANCH" == "main" && ( "$HEAD_BRANCH" == "production" || "$HEAD_BRANCH" == "staging" ) ]])
+
+          if [[ $IS_HEAD_PRODUCTION || $IS_HEAD_STAGING_BASE_NOT_PRODUCTION || $IS_BASE_STAGING_HEAD_NOT_MAIN || $IS_BASE_PRODUCTION_HEAD_NOT_STAGING || $IS_BASE_MAIN_HEAD_PRODUCTION_OR_STAGING ]]; then
+            echo "Error: Branch conditions are not met."
+            exit 1
+          fi
